-- MySQL Script generated by MySQL Workbench
-- Thứ tư, 07 Tháng 2 Năm 2018 10:34:05 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema assigment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assigment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assigment` DEFAULT CHARACTER SET latin1 ;
USE `assigment` ;

-- -----------------------------------------------------
-- Table `assigment`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assigment`.`location` (
  `location_code` INT(11) NOT NULL AUTO_INCREMENT,
  `location_decription` VARCHAR(225) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`location_code`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `assigment`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assigment`.`employees` (
  `employee_id` INT(11) NOT NULL AUTO_INCREMENT,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `other_details` VARCHAR(225) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `assigment`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assigment`.`projects` (
  `project_id` INT(11) NOT NULL AUTO_INCREMENT,
  `location_code` INT(11) NOT NULL,
  `project_mgr_employee_id` INT(11) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `other_details` VARCHAR(225) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `location_code` (`location_code` ASC, `project_mgr_employee_id` ASC),
  INDEX `project_mgr_employee_id` (`project_mgr_employee_id` ASC),
  CONSTRAINT `projects_ibfk_1`
    FOREIGN KEY (`location_code`)
    REFERENCES `assigment`.`location` (`location_code`),
  CONSTRAINT `projects_ibfk_2`
    FOREIGN KEY (`project_mgr_employee_id`)
    REFERENCES `assigment`.`employees` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `assigment`.`activity_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assigment`.`activity_codes` (
  `activity_code` INT(11) NOT NULL AUTO_INCREMENT,
  `activity_description` VARCHAR(225) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`activity_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `assigment`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assigment`.`activities` (
  `activity_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(11) NULL DEFAULT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `other_details` VARCHAR(225) CHARACTER SET 'utf8' NOT NULL,
  `activity_codes_activity_code` INT(11) NOT NULL,
  PRIMARY KEY (`activity_id`),
  INDEX `project_id` (`project_id` ASC),
  INDEX `fk_activities_activity_codes1_idx` (`activity_codes_activity_code` ASC),
  CONSTRAINT `activities_ibfk_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `assigment`.`projects` (`project_id`),
  CONSTRAINT `fk_activities_activity_codes1`
    FOREIGN KEY (`activity_codes_activity_code`)
    REFERENCES `assigment`.`activity_codes` (`activity_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `assigment`.`cost_centers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assigment`.`cost_centers` (
  `cost_center_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cost_center_name` VARCHAR(125) CHARACTER SET 'utf8' NOT NULL,
  `cost_center_decription` VARCHAR(225) CHARACTER SET 'utf8' NOT NULL,
  `other_details` VARCHAR(225) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`cost_center_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `assigment`.`timesheets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assigment`.`timesheets` (
  `timesheet_id` INT(11) NOT NULL AUTO_INCREMENT,
  `activity_id` INT(11) NOT NULL,
  `cost_center_id` INT(11) NOT NULL,
  `timesheet_for_employee_id` INT(11) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `submitted_date` DATETIME NOT NULL,
  `other_details` VARCHAR(225) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`timesheet_id`),
  INDEX `activity_id` (`activity_id` ASC, `cost_center_id` ASC, `timesheet_for_employee_id` ASC),
  INDEX `cost_center_id` (`cost_center_id` ASC),
  INDEX `timesheet_for_employee_id` (`timesheet_for_employee_id` ASC),
  CONSTRAINT `timesheets_ibfk_1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `assigment`.`activities` (`activity_id`),
  CONSTRAINT `timesheets_ibfk_3`
    FOREIGN KEY (`cost_center_id`)
    REFERENCES `assigment`.`cost_centers` (`cost_center_id`),
  CONSTRAINT `timesheets_ibfk_4`
    FOREIGN KEY (`timesheet_for_employee_id`)
    REFERENCES `assigment`.`employees` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
